import type {
    AreaDefinition,
    DoorDefinition,
    FixedEquipmentDefinition,
    FurnitureCategory,
    FurnitureDefinition,
    FurniturePlacementRule,
    OpeningDefinition,
    RoomDefinition,
    RoomSize,
    WallDefinition,
    WindowDefinition,
} from './types';

export const floorPlanVersion = 'floorplan-20260427';

export const roomSize: RoomSize = {
    width: 6.2,
    depth: 12.2,
};

export const balconySize: RoomSize = {
    width: 6.2,
    depth: 2.0,
};

export const ceilingHeight = 2.45;
export const wallThickness = 0.15;

export const roomBounds = {
    minX: -3.1,
    maxX: 3.1,
    minZ: -6.1,
    maxZ: 8.1,
};

export const rooms: RoomDefinition[] = [
    {
        id: 'entrance',
        name: '玄関',
        type: 'entrance',
        position: { x: 0, z: -5.55 },
        size: { width: 1.05, depth: 1.1 },
        height: ceilingHeight,
        floorMaterial: 'tileWhite',
        wallMaterial: 'wallWarmWhite',
        openings: ['entrance-to-corridor'],
        doors: ['front-door'],
        windows: [],
    },
    {
        id: 'corridor',
        name: '廊下',
        type: 'corridor',
        position: { x: 0, z: -1.2 },
        size: { width: 1.05, depth: 8.2 },
        height: ceilingHeight,
        floorMaterial: 'floorOak',
        wallMaterial: 'wallWarmWhite',
        openings: ['entrance-to-corridor', 'corridor-to-living'],
        doors: ['bedroom1-door', 'service-room-door', 'toilet-door', 'washroom-door', 'bedroom2-door'],
        windows: [],
    },
    {
        id: 'livingDining',
        name: 'リビング・ダイニング 約11.8畳',
        type: 'livingDining',
        position: { x: 0, z: 4.65 },
        size: { width: 6.2, depth: 2.9 },
        height: ceilingHeight,
        floorMaterial: 'floorOak',
        wallMaterial: 'wallWarmWhite',
        openings: ['corridor-to-living', 'living-balcony-opening', 'kitchen-counter-opening'],
        doors: [],
        windows: ['balcony-window'],
    },
    {
        id: 'kitchen',
        name: 'キッチン 約3.4畳',
        type: 'kitchen',
        position: { x: -2.0, z: 2.0 },
        size: { width: 2.2, depth: 2.7 },
        height: ceilingHeight,
        floorMaterial: 'floorOak',
        wallMaterial: 'wallWarmWhite',
        openings: ['kitchen-counter-opening'],
        doors: [],
        windows: [],
    },
    {
        id: 'bedroom1',
        name: '洋室(1) 約4.5畳',
        type: 'bedroom',
        position: { x: -1.85, z: -4.65 },
        size: { width: 2.5, depth: 2.9 },
        height: ceilingHeight,
        floorMaterial: 'floorOak',
        wallMaterial: 'wallWarmWhite',
        openings: [],
        doors: ['bedroom1-door'],
        windows: ['bedroom1-window'],
    },
    {
        id: 'serviceRoom',
        name: 'サービスルーム 約6.0畳',
        type: 'serviceRoom',
        position: { x: 1.82, z: -4.3 },
        size: { width: 2.55, depth: 3.6 },
        height: ceilingHeight,
        floorMaterial: 'floorOak',
        wallMaterial: 'wallWarmWhite',
        openings: ['service-room-closet-opening'],
        doors: ['service-room-door'],
        windows: ['service-room-window'],
    },
    {
        id: 'walkThroughCloset',
        name: 'ウォーククロゼット／可動収納',
        type: 'closet',
        position: { x: 1.82, z: -1.95 },
        size: { width: 2.55, depth: 0.9 },
        height: ceilingHeight,
        floorMaterial: 'floorOak',
        wallMaterial: 'wallWarmWhite',
        openings: ['service-room-closet-opening', 'closet-bedroom2-opening'],
        doors: [],
        windows: [],
    },
    {
        id: 'bedroom2',
        name: '洋室(2) 約4.4畳',
        type: 'bedroom',
        position: { x: 1.82, z: 0.25 },
        size: { width: 2.55, depth: 3.0 },
        height: ceilingHeight,
        floorMaterial: 'floorOak',
        wallMaterial: 'wallWarmWhite',
        openings: ['closet-bedroom2-opening', 'bedroom2-wall-door'],
        doors: ['bedroom2-door'],
        windows: [],
    },
    {
        id: 'bathroom',
        name: '浴室 1418',
        type: 'bathroom',
        position: { x: -2.4, z: -2.2 },
        size: { width: 1.4, depth: 1.8 },
        height: ceilingHeight,
        floorMaterial: 'tileWhite',
        wallMaterial: 'wallWarmWhite',
        openings: [],
        doors: ['bathroom-door'],
        windows: [],
    },
    {
        id: 'washroom',
        name: '洗面室',
        type: 'washroom',
        position: { x: -2.4, z: -0.55 },
        size: { width: 1.4, depth: 1.5 },
        height: ceilingHeight,
        floorMaterial: 'tileWhite',
        wallMaterial: 'wallWarmWhite',
        openings: [],
        doors: ['washroom-door', 'bathroom-door'],
        windows: [],
    },
    {
        id: 'toilet',
        name: 'トイレ',
        type: 'toilet',
        position: { x: -0.95, z: -1.55 },
        size: { width: 0.8, depth: 1.35 },
        height: ceilingHeight,
        floorMaterial: 'tileWhite',
        wallMaterial: 'wallWarmWhite',
        openings: [],
        doors: ['toilet-door'],
        windows: [],
    },
    {
        id: 'balcony',
        name: 'バルコニー',
        type: 'balcony',
        position: { x: 0, z: 7.1 },
        size: balconySize,
        height: 1.2,
        floorMaterial: 'balconyConcrete',
        wallMaterial: 'balconyConcrete',
        openings: ['living-balcony-opening'],
        doors: [],
        windows: [],
    },
];

export const walkableAreas: AreaDefinition[] = [
    { id: 'entrance', name: '玄関', position: { x: 0, z: -5.55 }, size: { width: 0.88, depth: 0.92 } },
    { id: 'corridor', name: '廊下', position: { x: 0, z: -1.2 }, size: { width: 1.2, depth: 8.65 } },
    { id: 'livingDining', name: 'リビング・ダイニング', position: { x: 0, z: 4.55 }, size: { width: 5.85, depth: 3.0 } },
    { id: 'kitchen', name: 'キッチン', position: { x: -2.0, z: 2.0 }, size: { width: 1.85, depth: 2.55 } },
    { id: 'bedroom1', name: '洋室(1)', position: { x: -1.85, z: -4.65 }, size: { width: 2.5, depth: 2.52 } },
    { id: 'serviceRoom', name: 'サービスルーム', position: { x: 1.82, z: -4.3 }, size: { width: 2.44, depth: 3.2 } },
    { id: 'walkThroughCloset', name: 'ウォーククロゼット／可動収納', position: { x: 1.82, z: -1.95 }, size: { width: 2.15, depth: 0.62 } },
    { id: 'bedroom2', name: '洋室(2)', position: { x: 1.82, z: 0.25 }, size: { width: 2.45, depth: 2.62 } },
    { id: 'bathroom', name: '浴室', position: { x: -2.4, z: -2.2 }, size: { width: 1.12, depth: 1.5 } },
    { id: 'washroom', name: '洗面室', position: { x: -2.4, z: -0.55 }, size: { width: 1.12, depth: 1.18 } },
    { id: 'toilet', name: 'トイレ', position: { x: -0.95, z: -1.55 }, size: { width: 0.52, depth: 1.02 } },
    { id: 'balcony', name: 'バルコニー', position: { x: 0, z: 7.1 }, size: { width: 5.75, depth: 1.65 } },
];

export const placementAreas: AreaDefinition[] = [
    { id: 'livingDining', name: 'リビング・ダイニング', position: { x: 0, z: 4.45 }, size: { width: 5.72, depth: 3.1 } },
    { id: 'bedroom1', name: '洋室(1)', position: { x: -1.85, z: -4.65 }, size: { width: 2.12, depth: 2.42 } },
    { id: 'serviceRoom', name: 'サービスルーム', position: { x: 1.82, z: -4.3 }, size: { width: 2.15, depth: 3.05 } },
    { id: 'bedroom2', name: '洋室(2)', position: { x: 1.82, z: 0.25 }, size: { width: 2.15, depth: 2.5 } },
];

export const furniturePlacementRules: Record<FurnitureCategory, FurniturePlacementRule> = {
    sofa: { category: 'sofa', preferredAreaId: 'livingDining', areaIds: ['livingDining'] },
    tvBoard: { category: 'tvBoard', preferredAreaId: 'livingDining', areaIds: ['livingDining'] },
    tv: { category: 'tv', preferredAreaId: 'livingDining', areaIds: ['livingDining'] },
    diningTable: { category: 'diningTable', preferredAreaId: 'livingDining', areaIds: ['livingDining'] },
    chair: { category: 'chair', preferredAreaId: 'livingDining', areaIds: ['livingDining', 'bedroom1', 'bedroom2', 'serviceRoom'] },
    rug: { category: 'rug', preferredAreaId: 'livingDining', areaIds: ['livingDining'] },
    desk: { category: 'desk', preferredAreaId: 'bedroom2', areaIds: ['bedroom1', 'bedroom2', 'serviceRoom', 'livingDining'] },
    bed: { category: 'bed', preferredAreaId: 'bedroom1', areaIds: ['bedroom1', 'bedroom2', 'serviceRoom'] },
    shelf: { category: 'shelf', preferredAreaId: 'serviceRoom', areaIds: ['bedroom1', 'bedroom2', 'serviceRoom', 'livingDining'] },
};

export const walls: WallDefinition[] = [
    { id: 'outer-top-left', name: '外壁 北西', start: { x: -3.1, z: -6.1 }, end: { x: -0.62, z: -6.1 }, height: ceilingHeight, thickness: wallThickness, material: 'wallWarmWhite' },
    { id: 'outer-top-right', name: '外壁 北東', start: { x: 0.62, z: -6.1 }, end: { x: 3.1, z: -6.1 }, height: ceilingHeight, thickness: wallThickness, material: 'wallWarmWhite' },
    { id: 'outer-left-north', name: '外壁 西 北側', start: { x: -3.1, z: -6.1 }, end: { x: -3.1, z: -5.43 }, height: ceilingHeight, thickness: wallThickness, material: 'wallWarmWhite' },
    { id: 'outer-left-south', name: '外壁 西 南側', start: { x: -3.1, z: -4.17 }, end: { x: -3.1, z: 6.1 }, height: ceilingHeight, thickness: wallThickness, material: 'wallWarmWhite' },
    { id: 'outer-right-north', name: '外壁 東 北側', start: { x: 3.1, z: -6.1 }, end: { x: 3.1, z: -5.33 }, height: ceilingHeight, thickness: wallThickness, material: 'wallWarmWhite' },
    { id: 'outer-right-south', name: '外壁 東 南側', start: { x: 3.1, z: -3.97 }, end: { x: 3.1, z: 6.1 }, height: ceilingHeight, thickness: wallThickness, material: 'wallWarmWhite' },
    { id: 'living-south-left', name: 'バルコニー側袖壁 左', start: { x: -3.1, z: 6.1 }, end: { x: -2.35, z: 6.1 }, height: ceilingHeight, thickness: wallThickness, material: 'wallWarmWhite' },
    { id: 'living-south-right', name: 'バルコニー側袖壁 右', start: { x: 2.35, z: 6.1 }, end: { x: 3.1, z: 6.1 }, height: ceilingHeight, thickness: wallThickness, material: 'wallWarmWhite' },
    { id: 'bedroom1-south', name: '洋室(1)南壁', start: { x: -3.1, z: -3.2 }, end: { x: -0.55, z: -3.2 }, height: ceilingHeight, thickness: wallThickness, material: 'wallWarmWhite' },
    { id: 'bedroom1-east-a', name: '洋室(1)廊下壁 上', start: { x: -0.55, z: -6.1 }, end: { x: -0.55, z: -5.1 }, height: ceilingHeight, thickness: wallThickness, material: 'wallWarmWhite' },
    { id: 'bedroom1-east-b', name: '洋室(1)廊下壁 下', start: { x: -0.55, z: -4.35 }, end: { x: -0.55, z: -3.2 }, height: ceilingHeight, thickness: wallThickness, material: 'wallWarmWhite' },
    { id: 'service-west-a', name: 'サービスルーム廊下壁 上', start: { x: 0.55, z: -6.1 }, end: { x: 0.55, z: -5.05 }, height: ceilingHeight, thickness: wallThickness, material: 'wallWarmWhite' },
    { id: 'service-west-b', name: 'サービスルーム廊下壁 下', start: { x: 0.55, z: -4.3 }, end: { x: 0.55, z: -2.5 }, height: ceilingHeight, thickness: wallThickness, material: 'wallWarmWhite' },
    { id: 'service-south', name: 'サービスルーム南壁', start: { x: 0.55, z: -2.5 }, end: { x: 3.1, z: -2.5 }, height: ceilingHeight, thickness: wallThickness, material: 'wallWarmWhite' },
    { id: 'closet-south', name: '可動収納南壁', start: { x: 0.55, z: -1.45 }, end: { x: 3.1, z: -1.45 }, height: ceilingHeight, thickness: wallThickness, material: 'wallWarmWhite' },
    { id: 'bedroom2-west-a', name: '洋室(2)廊下壁 上', start: { x: 0.55, z: -1.45 }, end: { x: 0.55, z: -0.45 }, height: ceilingHeight, thickness: wallThickness, material: 'wallWarmWhite' },
    { id: 'bedroom2-west-b', name: '洋室(2)廊下壁 下', start: { x: 0.55, z: 0.3 }, end: { x: 0.55, z: 1.75 }, height: ceilingHeight, thickness: wallThickness, material: 'wallWarmWhite' },
    { id: 'bedroom2-south-left', name: '洋室(2)ウォールドア 袖壁左', start: { x: 0.55, z: 1.75 }, end: { x: 0.92, z: 1.75 }, height: ceilingHeight, thickness: 0.08, material: 'wallWarmWhite' },
    { id: 'bedroom2-south-right', name: '洋室(2)ウォールドア 袖壁右', start: { x: 2.72, z: 1.75 }, end: { x: 3.1, z: 1.75 }, height: ceilingHeight, thickness: 0.08, material: 'wallWarmWhite' },
    { id: 'living-north-right', name: 'LD北側壁 右', start: { x: 0.55, z: 3.2 }, end: { x: 3.1, z: 3.2 }, height: ceilingHeight, thickness: wallThickness, material: 'wallWarmWhite' },
    { id: 'kitchen-east', name: 'キッチン腰壁側', start: { x: -0.85, z: 0.65 }, end: { x: -0.85, z: 3.2 }, height: 1.05, thickness: 0.12, material: 'whiteMatte' },
    { id: 'kitchen-north', name: 'キッチン北壁', start: { x: -3.1, z: 0.65 }, end: { x: -0.85, z: 0.65 }, height: ceilingHeight, thickness: wallThickness, material: 'wallWarmWhite' },
    { id: 'bath-east', name: '浴室東壁', start: { x: -1.7, z: -3.1 }, end: { x: -1.7, z: -1.25 }, height: ceilingHeight, thickness: wallThickness, material: 'wallWarmWhite' },
    { id: 'bath-south', name: '浴室南壁', start: { x: -3.1, z: -1.25 }, end: { x: -1.7, z: -1.25 }, height: ceilingHeight, thickness: wallThickness, material: 'wallWarmWhite' },
    { id: 'wash-east', name: '洗面室東壁', start: { x: -1.7, z: -1.25 }, end: { x: -1.7, z: 0.2 }, height: ceilingHeight, thickness: wallThickness, material: 'wallWarmWhite' },
    { id: 'wash-south', name: '洗面室南壁', start: { x: -3.1, z: 0.2 }, end: { x: -1.7, z: 0.2 }, height: ceilingHeight, thickness: wallThickness, material: 'wallWarmWhite' },
    { id: 'toilet-east', name: 'トイレ東壁', start: { x: -0.55, z: -2.25 }, end: { x: -0.55, z: -0.85 }, height: ceilingHeight, thickness: wallThickness, material: 'wallWarmWhite' },
    { id: 'toilet-west', name: 'トイレ西壁', start: { x: -1.35, z: -2.25 }, end: { x: -1.35, z: -0.85 }, height: ceilingHeight, thickness: wallThickness, material: 'wallWarmWhite' },
    { id: 'toilet-north', name: 'トイレ北壁', start: { x: -1.35, z: -2.25 }, end: { x: -0.55, z: -2.25 }, height: ceilingHeight, thickness: wallThickness, material: 'wallWarmWhite' },
    { id: 'corridor-living-left', name: '廊下LD左袖壁', start: { x: -0.55, z: 0.2 }, end: { x: -0.55, z: 3.2 }, height: ceilingHeight, thickness: wallThickness, material: 'wallWarmWhite' },
];

export const windows: WindowDefinition[] = [
    { id: 'balcony-window', name: 'バルコニー側掃き出し窓', position: { x: 0, z: 6.08 }, width: 4.7, height: 2.0, sillHeight: 0.05, orientation: 'south', material: 'glass' },
    { id: 'bedroom1-window', name: '洋室(1)窓', position: { x: -3.08, z: -4.8 }, width: 1.25, height: 1.15, sillHeight: 0.85, orientation: 'west', material: 'glass' },
    { id: 'service-room-window', name: 'サービスルーム窓', position: { x: 3.08, z: -4.65 }, width: 1.35, height: 1.15, sillHeight: 0.85, orientation: 'east', material: 'glass' },
];

export const doors: DoorDefinition[] = [
    { id: 'front-door', name: '玄関ドア', position: { x: 0, z: -6.08 }, width: 0.9, height: 2.0, orientation: 'north', swing: 'left' },
    { id: 'bedroom1-door', name: '洋室(1)ドア', position: { x: -0.55, z: -4.75 }, width: 0.75, height: 2.0, orientation: 'east', swing: 'left' },
    { id: 'service-room-door', name: 'サービスルームドア', position: { x: 0.55, z: -4.65 }, width: 0.75, height: 2.0, orientation: 'west', swing: 'right' },
    { id: 'toilet-door', name: 'トイレドア', position: { x: -0.55, z: -1.55 }, width: 0.68, height: 2.0, orientation: 'east', swing: 'left' },
    { id: 'washroom-door', name: '洗面室ドア', position: { x: -1.7, z: -0.55 }, width: 0.72, height: 2.0, orientation: 'east', swing: 'sliding' },
    { id: 'bathroom-door', name: '浴室ドア', position: { x: -2.4, z: -1.25 }, width: 0.72, height: 2.0, orientation: 'south', swing: 'sliding' },
    { id: 'bedroom2-door', name: '洋室(2)ドア', position: { x: 0.55, z: -0.05 }, width: 0.75, height: 2.0, orientation: 'west', swing: 'sliding' },
];

export const openings: OpeningDefinition[] = [
    { id: 'entrance-to-corridor', name: '玄関から廊下', position: { x: 0, z: -5.0 }, width: 1.0, orientation: 'south' },
    { id: 'corridor-to-living', name: '廊下からLD', position: { x: 0, z: 3.2 }, width: 1.05, orientation: 'south' },
    { id: 'living-balcony-opening', name: 'LDからバルコニー', position: { x: 0, z: 6.1 }, width: 4.7, orientation: 'south' },
    { id: 'kitchen-counter-opening', name: 'キッチンカウンター', position: { x: -0.85, z: 2.4 }, width: 1.6, orientation: 'east' },
    { id: 'service-room-closet-opening', name: 'サービスルーム収納開口', position: { x: 1.82, z: -2.5 }, width: 1.2, orientation: 'south' },
    { id: 'closet-bedroom2-opening', name: '収納から洋室(2)', position: { x: 1.82, z: -1.45 }, width: 1.2, orientation: 'south' },
    { id: 'bedroom2-wall-door', name: '洋室(2)ウォールドア', position: { x: 1.82, z: 1.75 }, width: 1.8, orientation: 'south' },
];

export const fixedEquipments: FixedEquipmentDefinition[] = [
    { id: 'kitchen-counter', name: 'キッチンカウンター', roomId: 'kitchen', category: 'kitchenCounter', position: { x: -1.0, z: 2.62 }, size: { width: 0.18, depth: 1.55, height: 0.95 }, rotation: 0, material: 'whiteMatte' },
    { id: 'kitchen-worktop', name: '作業台', roomId: 'kitchen', category: 'kitchenCounter', position: { x: -2.55, z: 1.7 }, size: { width: 0.55, depth: 1.9, height: 0.86 }, rotation: 0, material: 'woodLight' },
    { id: 'kitchen-sink', name: 'シンク', roomId: 'kitchen', category: 'sink', position: { x: -2.55, z: 1.25 }, size: { width: 0.45, depth: 0.55, height: 0.08 }, rotation: 0, material: 'stoneGray' },
    { id: 'kitchen-cooktop', name: 'コンロ', roomId: 'kitchen', category: 'cooktop', position: { x: -2.55, z: 2.15 }, size: { width: 0.42, depth: 0.5, height: 0.05 }, rotation: 0, material: 'metalBlack' },
    { id: 'fridge-space', name: '冷蔵庫置場', roomId: 'kitchen', category: 'fridgeSpace', position: { x: -2.55, z: 3.0 }, size: { width: 0.65, depth: 0.65, height: 1.8 }, rotation: 0, material: 'whiteMatte' },
    { id: 'bath-tub', name: '浴槽', roomId: 'bathroom', category: 'bathTub', position: { x: -2.4, z: -2.45 }, size: { width: 1.15, depth: 0.72, height: 0.55 }, rotation: 0, material: 'whiteMatte' },
    { id: 'vanity', name: '洗面台', roomId: 'washroom', category: 'vanity', position: { x: -2.78, z: -0.65 }, size: { width: 0.45, depth: 0.62, height: 0.82 }, rotation: 0, material: 'whiteMatte' },
    { id: 'washer-pan', name: '防水パン', roomId: 'washroom', category: 'washerPan', position: { x: -2.02, z: -0.65 }, size: { width: 0.62, depth: 0.62, height: 0.08 }, rotation: 0, material: 'tileWhite' },
    { id: 'toilet-bowl', name: '便器', roomId: 'toilet', category: 'toiletBowl', position: { x: -0.95, z: -1.55 }, size: { width: 0.38, depth: 0.62, height: 0.45 }, rotation: 0, material: 'whiteMatte' },
    { id: 'bedroom1-closet', name: '洋室(1)クローゼット', roomId: 'bedroom1', category: 'closet', position: { x: -2.1, z: -3.45 }, size: { width: 1.35, depth: 0.3, height: 2.1 }, rotation: 0, material: 'whiteMatte' },
    { id: 'walk-closet-unit', name: '可動収納ユニット', roomId: 'walkThroughCloset', category: 'closet', position: { x: 2.15, z: -1.95 }, size: { width: 1.25, depth: 0.34, height: 2.05 }, rotation: 0, material: 'woodLight' },
    { id: 'balcony-rail-front', name: 'バルコニー手すり', roomId: 'balcony', category: 'balconyRail', position: { x: 0, z: 8.05 }, size: { width: 5.9, depth: 0.08, height: 1.1 }, rotation: 0, material: 'glass' },
    { id: 'balcony-rail-left', name: 'バルコニー左袖', roomId: 'balcony', category: 'balconyRail', position: { x: -3.05, z: 7.1 }, size: { width: 0.08, depth: 1.9, height: 1.1 }, rotation: 0, material: 'balconyConcrete' },
    { id: 'balcony-rail-right', name: 'バルコニー右袖', roomId: 'balcony', category: 'balconyRail', position: { x: 3.05, z: 7.1 }, size: { width: 0.08, depth: 1.9, height: 1.1 }, rotation: 0, material: 'balconyConcrete' },
];

export const initialFurniture: FurnitureDefinition[] = [
    { id: 'living-sofa', name: 'ソファ', category: 'sofa', size: { width: 1.8, depth: 0.86, height: 0.78 }, position: { x: -1.2, y: 0, z: 4.5 }, rotation: -90, color: '#8f9699', material: 'fabricGray', style: 'natural', variant: 'fabricGray', modelPath: '/models/furniture/sofa.glb', visible: true, fallbackGeometry: 'sofa', renderMode: 'simple' },
    { id: 'living-rug', name: 'ラグ', category: 'rug', size: { width: 1.8, depth: 1.2, height: 0.03 }, position: { x: 0.1, y: 0, z: 4.55 }, rotation: -90, color: '#c8b79f', material: 'fabricBeige', style: 'natural', variant: 'beige', visible: true, fallbackGeometry: 'rug', renderMode: 'simple' },
    { id: 'living-tv-board', name: 'テレビボード', category: 'tvBoard', size: { width: 1.6, depth: 0.38, height: 0.42 }, position: { x: 2.65, y: 0, z: 4.5 }, rotation: -90, color: '#cfa66a', material: 'woodLight', style: 'natural', variant: 'lightOak', modelPath: '/models/furniture/tv-board.glb', visible: true, fallbackGeometry: 'box', renderMode: 'simple' },
    { id: 'living-tv', name: 'テレビ', category: 'tv', size: { width: 1.22, depth: 0.08, height: 0.72 }, position: { x: 2.43, y: 0.42, z: 4.5 }, rotation: -90, color: '#111827', material: 'metalBlack', style: 'modern', variant: 'blackScreen', modelPath: '/models/furniture/tv.glb', visible: true, fallbackGeometry: 'tv', renderMode: 'simple' },
    { id: 'dining-table', name: 'ダイニングテーブル', category: 'diningTable', size: { width: 1.4, depth: 0.8, height: 0.72 }, position: { x: -1.75, y: 0, z: 3.55 }, rotation: 0, color: '#cfa66a', material: 'woodLight', style: 'natural', variant: 'naturalWood', modelPath: '/models/furniture/dining-table.glb', visible: true, fallbackGeometry: 'table', renderMode: 'simple' },
    { id: 'dining-chair-1', name: 'ダイニングチェア 1', category: 'chair', size: { width: 0.46, depth: 0.5, height: 0.82 }, position: { x: -1.75, y: 0, z: 2.95 }, rotation: 0, color: '#cfa66a', material: 'woodLight', style: 'natural', variant: 'wood', modelPath: '/models/furniture/chair.glb', visible: true, fallbackGeometry: 'chair', renderMode: 'simple' },
    { id: 'dining-chair-2', name: 'ダイニングチェア 2', category: 'chair', size: { width: 0.46, depth: 0.5, height: 0.82 }, position: { x: -1.75, y: 0, z: 4.15 }, rotation: 180, color: '#cfa66a', material: 'woodLight', style: 'natural', variant: 'wood', modelPath: '/models/furniture/chair.glb', visible: true, fallbackGeometry: 'chair', renderMode: 'simple' },
    { id: 'bedroom1-bed', name: '洋室(1)ベッド', category: 'bed', size: { width: 1.0, depth: 1.95, height: 0.52 }, position: { x: -2.35, y: 0, z: -4.65 }, rotation: 0, color: '#c8b79f', material: 'fabricBeige', style: 'natural', variant: 'beigeFabric', modelPath: '/models/furniture/bed.glb', visible: true, fallbackGeometry: 'bed', renderMode: 'simple' },
    { id: 'service-room-desk', name: 'サービスルーム デスク', category: 'desk', size: { width: 1.1, depth: 0.6, height: 0.72 }, position: { x: 2.25, y: 0, z: -5.25 }, rotation: 0, color: '#cfa66a', material: 'woodLight', style: 'natural', variant: 'naturalWood', modelPath: '/models/furniture/desk.glb', visible: true, fallbackGeometry: 'desk', renderMode: 'simple' },
    { id: 'service-room-shelf', name: 'サービスルーム 棚', category: 'shelf', size: { width: 0.9, depth: 0.34, height: 1.2 }, position: { x: 2.55, y: 0, z: -3.25 }, rotation: 90, color: '#cfa66a', material: 'woodLight', style: 'natural', variant: 'openRack', modelPath: '/models/furniture/shelf.glb', visible: true, fallbackGeometry: 'shelf', renderMode: 'simple' },
    { id: 'bedroom2-desk', name: '洋室(2)ワークデスク', category: 'desk', size: { width: 1.1, depth: 0.6, height: 0.72 }, position: { x: 2.25, y: 0, z: 0.95 }, rotation: 0, color: '#f8fafc', material: 'whiteMatte', style: 'scandinavian', variant: 'white', modelPath: '/models/furniture/desk.glb', visible: true, fallbackGeometry: 'desk', renderMode: 'simple' },
    { id: 'bedroom2-chair', name: '洋室(2)チェア', category: 'chair', size: { width: 0.46, depth: 0.5, height: 0.82 }, position: { x: 2.25, y: 0, z: 0.35 }, rotation: 0, color: '#8f9699', material: 'fabricGray', style: 'scandinavian', variant: 'fabric', modelPath: '/models/furniture/chair.glb', visible: true, fallbackGeometry: 'chair', renderMode: 'simple' },
];
